# Generated by Django 4.2.11 on 2024-11-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0025_capmenupermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capmenupermission',
            options={'default_permissions': [], 'permissions': (('can_view_alerts_menu', 'Can view CAP Alerts Menu'),), 'verbose_name': 'CAP Menu Permission', 'verbose_name_plural': 'CAP Menu Permissions'},
        ),
    ]
