# Generated by Django 4.2.16 on 2025-02-24 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0026_alter_capmenupermission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='capalertlistpage',
            name='alerts_infos_per_page',
            field=models.PositiveIntegerField(default=10, help_text='Number of alerts to show per page', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
