# Generated by Django 4.2.16 on 2025-04-29 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_newsletter', '0001_initial'),
        ('cap', '0030_alter_capalertpage_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='capalertpage',
            name='newsletter_campaign',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='capalertpage',
            name='newsletter_recipients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtail_newsletter.newsletterrecipients'),
        ),
        migrations.AddField(
            model_name='capalertpage',
            name='newsletter_subject',
            field=models.CharField(blank=True, help_text='Subject for the newsletter. Defaults to page title if blank.', max_length=1000),
        ),
    ]
