# Generated by Django 5.2.1 on 2025-09-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0031_capalertpage_newsletter_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capalertmqttbroker',
            name='qos',
            field=models.PositiveIntegerField(choices=[(0, 'At most once. Fire and forget'), (1, 'At least once. I’ll keep sending until you say you got it')], default=0, verbose_name='Quality of Service (QoS)'),
        ),
    ]
