# Generated by Django 5.2.12 on 2026-06-11 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0034_site_scoping'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capalertmqttbroker',
            name='site',
            field=models.ForeignKey(blank=True, help_text='The site this broker is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mqtt_brokers', to='wagtailcore.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='externalalertfeed',
            name='site',
            field=models.ForeignKey(blank=True, help_text='The site this feed is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_feeds', to='wagtailcore.site', verbose_name='Site'),
        ),
    ]
