# Generated by Django 5.2.1 on 2026-06-25 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0035_alter_capalertmqttbroker_site_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capalertmqttbrokerevent',
            options={'ordering': ['-created'], 'verbose_name': 'MQTT Broker Event', 'verbose_name_plural': 'MQTT Broker Events'},
        ),
        migrations.AlterModelOptions(
            name='capalertwebhookevent',
            options={'ordering': ['-created'], 'verbose_name': 'CAP Alert Webhook Event', 'verbose_name_plural': 'CAP Alert Webhook Events'},
        ),
        migrations.AddField(
            model_name='capalertmqttbrokerevent',
            name='source_event',
            field=models.ForeignKey(blank=True, help_text='The original event this republish was triggered from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='republishes', to='cap.capalertmqttbrokerevent', verbose_name='Republished from'),
        ),
        migrations.AddField(
            model_name='capalertwebhookevent',
            name='source_event',
            field=models.ForeignKey(blank=True, help_text='The original event this republish was triggered from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='republishes', to='cap.capalertwebhookevent', verbose_name='Republished from'),
        ),
    ]
