# Generated by Django 5.2.12 on 2026-08-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0036_alter_capalertmqttbrokerevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othercapsettings',
            name='active_alert_style',
            field=models.CharField(choices=[('nav_left', 'Left of the Navbar'), ('nav_top', 'Top of the Navbar')], default='nav_top', help_text='Choose the style of active alerts', max_length=50, verbose_name='Active Alert Style'),
        ),
    ]
