# Generated by Django 4.2.11 on 2024-11-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0024_alter_capalertpage_alert_pdf_preview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_view_alerts_menu', 'Can view CAP Alerts Menu'),),
                'default_permissions': [],
            },
        ),
    ]
