# Generated by Django 4.2.2 on 2023-06-26 10:41

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtailiconchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsetting',
            name='audience_types',
            field=wagtail.fields.StreamField([('audience_type', wagtail.blocks.StructBlock([('hazard', wagtail.blocks.CharBlock(help_text='Name of Hazard', label='Hazard', max_length=255)), ('icon', wagtailiconchooser.blocks.IconChooserBlock(required=False))], label='Hazard Type'))], blank=True, null=True, use_json_field=True, verbose_name='Hazard Types'),
        ),
    ]
