# Generated by Django 4.2.2 on 2023-06-26 11:49

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtailiconchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0002_capsetting_audience_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsetting',
            name='audience_types',
            field=wagtail.fields.StreamField([('audience_type', wagtail.blocks.StructBlock([('audience', wagtail.blocks.CharBlock(help_text='Intended audience', label='Audience', max_length=255))], label='Audience Type'))], blank=True, help_text='Target audiences for published alerts', null=True, use_json_field=True, verbose_name='Audience Types'),
        ),
        migrations.AlterField(
            model_name='capsetting',
            name='contact',
            field=models.CharField(blank=True, help_text='Contact details of the sending institution. Can be an official email address of the institution or a link to the contact us form', max_length=255, null=True, verbose_name='CAP Sender Contact'),
        ),
        migrations.AlterField(
            model_name='capsetting',
            name='hazard_types',
            field=wagtail.fields.StreamField([('hazard_type', wagtail.blocks.StructBlock([('hazard', wagtail.blocks.CharBlock(help_text='Name of Hazard', label='Hazard', max_length=255)), ('icon', wagtailiconchooser.blocks.IconChooserBlock(required=False))], label='Hazard Type'))], blank=True, help_text='Hazards monitored by the institution', null=True, use_json_field=True, verbose_name='Hazard Types'),
        ),
        migrations.AlterField(
            model_name='capsetting',
            name='sender',
            field=models.CharField(blank=True, help_text='Can be the website link or email of the sending institution', max_length=255, null=True, verbose_name='CAP Sender Identifier'),
        ),
        migrations.AlterField(
            model_name='capsetting',
            name='sender_name',
            field=models.CharField(blank=True, help_text='Name of the sending institution', max_length=255, null=True, verbose_name='CAP Sender Name'),
        ),
    ]
