# Generated by Django 4.1.7 on 2023-03-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0002_alertlist_alerts_per_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertinfo',
            name='description',
            field=models.TextField(blank=True, help_text='The text describing the subject event of the alert message', null=True),
        ),
        migrations.AlterField(
            model_name='alertinfo',
            name='instruction',
            field=models.TextField(blank=True, help_text='The text describing the recommended action to be taken by recipients of the alert message', null=True),
        ),
    ]
