# Generated by Django 4.2.2 on 2023-06-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0003_alter_abstractcapalertpage_alert_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstractcapalertpage',
            old_name='alert_info',
            new_name='info',
        ),
    ]
