# Generated by Django 4.2.2 on 2023-07-03 12:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0003_alter_capsetting_audience_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_0', models.CharField(blank=True, max_length=100, null=True)),
                ('name_1', models.CharField(blank=True, max_length=100, null=True)),
                ('name_2', models.CharField(blank=True, max_length=100, null=True)),
                ('gid_0', models.CharField(blank=True, max_length=100, null=True)),
                ('gid_1', models.CharField(blank=True, max_length=100, null=True)),
                ('gid_2', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Country Boundaries',
            },
        ),
    ]
