# Generated by Django 4.1.10 on 2023-07-07 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0004_countryboundary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryBoundary',
        ),
    ]
