# Generated by Django 4.1.10 on 2023-07-09 13:21

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0005_delete_countryboundary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsetting',
            name='contact',
        ),
        migrations.AddField(
            model_name='capsetting',
            name='contacts',
            field=wagtail.fields.StreamField([('contact', wagtail.blocks.StructBlock([('contact', wagtail.blocks.CharBlock(label='Contact Detail', max_length=255))], label='Contact'))], blank=True, help_text='Contact for follow-up and confirmation of the alert message', null=True, use_json_field=True, verbose_name='Contact Details'),
        ),
    ]
