# Generated by Django 4.1.7 on 2023-04-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0005_rename_message_type_alert_msgtype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertresource',
            old_name='resource_desc',
            new_name='resourceDesc',
        ),
        migrations.RemoveField(
            model_name='alertresource',
            name='link',
        ),
        migrations.AddField(
            model_name='alertresource',
            name='uri',
            field=models.URLField(blank=True, help_text='The identifier of the hyperlink for the resource file', null=True, verbose_name='link'),
        ),
    ]
