# Generated by Django 4.2.2 on 2023-06-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0006_alter_abstractcapalertpage_info_capsetting_capsender'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsetting',
            name='sender',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CAP Sender'),
        ),
        migrations.AddField(
            model_name='capsetting',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CAP Sender Name'),
        ),
        migrations.AlterField(
            model_name='capsetting',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CAP Sender Contact'),
        ),
    ]
