# Generated by Django 4.1.7 on 2023-04-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0006_rename_resource_desc_alertresource_resourcedesc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertresource',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
