# Generated by Django 4.2.16 on 2025-02-24 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0012_alter_hazardeventtypes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsetting',
            name='num_of_latest_alerts_in_feed',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Number of Latest Alerts to show in the CAP Feed. Set a smaller number to improve perfomance for aggregators'),
        ),
    ]
