# Generated by Django 4.2.16 on 2025-03-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0014_alter_capsetting_num_of_latest_alerts_in_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardeventtypes',
            name='category',
            field=models.CharField(choices=[('Geo', 'Geophysical'), ('Met', 'Meteorological'), ('Safety', 'General emergency and public safety'), ('Security', 'Law enforcement, military, homeland and local/private security'), ('Rescue', 'Rescue and recovery'), ('Fire', 'Fire suppression and rescue'), ('Health', 'Medical and public health'), ('Env', 'Pollution and other environmental'), ('Transport', 'Public and private transportation'), ('Infra', 'Utility, telecommunication, other non-transport infrastructure'), ('CBRNE', 'Chemical, Biological, Radiological, Nuclear or High-Yield Explosive threat or attack'), ('Other', 'Other events')], default='Met', help_text='Category of Hazard', max_length=35, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='hazardeventtypes',
            name='event_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Event Code'),
        ),
    ]
