# Generated by Django 4.2.16 on 2025-04-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0015_hazardeventtypes_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedalertarea',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
