# Generated by Django 5.2.12 on 2026-03-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0016_alter_predefinedalertarea_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsetting',
            name='wmo_oid',
            field=models.CharField(blank=True, help_text="WMO Register of Alerting Authorities Object Identifier (OID) of the sending institution. This will be used to generate CAP messages identifiers. Visit <a href='https://etrp.wmo.int/pluginfile.php/17873/mod_resource/content/1/AIR_PWS-20.pdf' target='_blank' rel='noopener'>WMO/TD No. 1556</a> for more information.", max_length=255, null=True, verbose_name='WMO Register of Alerting Authorities OID'),
        ),
    ]
