# Generated by Django 5.2.1 on 2026-04-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0017_alter_capsetting_wmo_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsetting',
            name='intersection_area_threshold',
            field=models.PositiveIntegerField(default=1000, verbose_name='Intersection Area Threshold'),
        ),
    ]
