# Generated by Django 5.2.12 on 2026-04-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0018_capsetting_intersection_area_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsetting',
            name='intersection_area_threshold',
            field=models.PositiveIntegerField(default=1000, help_text='The maximum allowed overlap between two alert areas, in square meters. Areas that overlap by more than this value will be flagged as intersecting. The default of 1000m² accounts for small boundary imprecisions between adjacent areas. Increase this value if adjacent areas from your boundary data share imprecise borders.', verbose_name='Intersection Area Threshold (m²)'),
        ),
    ]
