# Generated by Django 5.2.1 on 2026-06-25 11:15

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0019_alter_capsetting_intersection_area_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertlanguage',
            name='setting',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_languages', to='capeditor.capsetting'),
        ),
        migrations.AlterField(
            model_name='hazardeventtypes',
            name='setting',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazard_event_types', to='capeditor.capsetting'),
        ),
        migrations.AlterField(
            model_name='predefinedalertarea',
            name='setting',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='predefined_alert_areas', to='capeditor.capsetting'),
        ),
    ]
