# Generated by Django 4.2.16 on 2025-02-24 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0013_capsetting_num_of_latest_alerts_in_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsetting',
            name='num_of_latest_alerts_in_feed',
            field=models.PositiveIntegerField(default=5, help_text='Set a smaller number to improve perfomance for aggregators', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Number of latest Alerts to show in the XML CAP Feed'),
        ),
    ]
