# Generated by Django 4.2.2 on 2023-06-18 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capeditor', '0001_initial'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapAlertPAge',
            fields=[
                ('abstractcapalertpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='capeditor.abstractcapalertpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('capeditor.abstractcapalertpage', 'wagtailcore.page'),
        ),
    ]
