# Generated by Django 4.1.10 on 2023-07-07 08:55

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_capalertpage_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='capalertpage',
            name='addresses',
            field=wagtail.fields.StreamField([('recipient', wagtail.blocks.StructBlock([('name', wagtail.blocks.TextBlock(label='Name of the recipient')), ('address', wagtail.blocks.EmailBlock(help_text='Email address', label='Email', required=True))], label='Recipient'))], blank=True, null=True, use_json_field=True, verbose_name='Recipient'),
        ),
    ]
