# Generated by Django 4.1.10 on 2023-07-07 11:20

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_capalertpage_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='capalertpage',
            name='references',
            field=wagtail.fields.StreamField([('reference', wagtail.blocks.StructBlock([('ref_alert', wagtail.blocks.PageChooserBlock(help_text='Earlier alert referenced by this alert', label='Reference Alert'))], label='Reference Alert'))], blank=True, null=True, use_json_field=True, verbose_name='Reference Alerts'),
        ),
        migrations.AlterField(
            model_name='capalertpage',
            name='addresses',
            field=wagtail.fields.StreamField([('recipient', wagtail.blocks.StructBlock([('name', wagtail.blocks.TextBlock(help_text='Name of the recipient', label='Name')), ('address', wagtail.blocks.TextBlock(help_text='Address Information of the recipient', label='Address'))], label='Recipient'))], blank=True, help_text='The group listing of intended recipients of the alert message, if scope is Private', null=True, use_json_field=True, verbose_name='Recipients'),
        ),
    ]
