# Generated by Django 4.1.10 on 2023-08-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_capalertpage_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CapAlertPage',
        ),
    ]
