# Generated by Django 4.1.13 on 2023-11-14 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_capalertpage_options_alter_capalertpage_info'),
        ('home', '0015_alter_capalertpage_info'),
    ]

    operations = [
    ]
