# Generated by Django 4.2.11 on 2024-06-03 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0023_alter_capalertpage_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capalertpage',
            old_name='identifier',
            new_name='guid'
        )
    ]
