# Generated by Django 4.2.3 on 2024-04-24 14:09

from django.db import migrations, models
import django.db.models.deletion
from wagtail.documents import get_document_model_string


class Migration(migrations.Migration):
    dependencies = [
        ('cap', '0012_alter_capalertpage_info_and_more'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='capalertpage',
            name='alert_pdf_preview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to=get_document_model_string()),
        ),
    ]
