# Generated by Django 4.2.7 on 2024-11-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0022_externalalertfeed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capalertpage',
            name='sender',
            field=models.CharField(help_text='Identifies the originator of an alert. For example the website address of the institution', max_length=255, verbose_name='Sender'),
        ),
    ]
