# Generated by Django 4.2.11 on 2024-11-18 11:56

import django.db.models.deletion
from django.db import migrations, models
from wagtail.documents import get_document_model_string


class Migration(migrations.Migration):
    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('cap', '0023_alter_capalertpage_sender'),
    ]
    
    operations = [
        migrations.AlterField(
            model_name='capalertpage',
            name='alert_pdf_preview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to=get_document_model_string()),
        ),
    ]
