# Generated by Django 4.2.16 on 2025-04-04 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0029_capalertpage_imported_alter_capalertpage_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capalertpage',
            name='sent',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time and date of origination of the alert. Automatically generated by the system during publishing', verbose_name='Sent'),
        ),
    ]
