# Generated by Django 5.2.1 on 2025-09-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0032_capalertmqttbroker_qos'),
    ]

    operations = [
        migrations.AddField(
            model_name='capalertwebhook',
            name='header_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Header Value'),
        ),
        migrations.AddField(
            model_name='capalertwebhook',
            name='include_auth_header',
            field=models.BooleanField(default=False, verbose_name='Include Header for Authentication'),
        ),
    ]
